export const kanjiDatabase = {
    grade1: [
        {kanji: '一', reading: 'いち', meaning: 'one'},
        {kanji: '二', reading: 'に', meaning: 'two'},
        {kanji: '三', reading: 'さん', meaning: 'three'},
        {kanji: '四', reading: 'よん', meaning: 'four'},
        {kanji: '五', reading: 'ご', meaning: 'five'},
        {kanji: '六', reading: 'ろく', meaning: 'six'},
        {kanji: '七', reading: 'なな', meaning: 'seven'},
        {kanji: '八', reading: 'はち', meaning: 'eight'},
        {kanji: '九', reading: 'きゅう', meaning: 'nine'},
        {kanji: '十', reading: 'じゅう', meaning: 'ten'},
        {kanji: '人', reading: 'ひと', meaning: 'person'},
        {kanji: '大', reading: 'おおきい', meaning: 'big'},
        {kanji: '小', reading: 'ちいさい', meaning: 'small'},
        {kanji: '水', reading: 'みず', meaning: 'water'},
        {kanji: '火', reading: 'ひ', meaning: 'fire'},
        {kanji: '土', reading: 'つち', meaning: 'soil'},
        {kanji: '木', reading: 'き', meaning: 'tree'},
        {kanji: '金', reading: 'きん', meaning: 'gold'},
        {kanji: '月', reading: 'つき', meaning: 'moon'},
        {kanji: '日', reading: 'ひ', meaning: 'sun'}
    ],
    grade2: [
        {kanji: '犬', reading: 'いぬ', meaning: 'dog'},
        {kanji: '猫', reading: 'ねこ', meaning: 'cat'},
        {kanji: '鳥', reading: 'とり', meaning: 'bird'},
        {kanji: '魚', reading: 'さかな', meaning: 'fish'},
        {kanji: '馬', reading: 'うま', meaning: 'horse'},
        {kanji: '牛', reading: 'うし', meaning: 'cow'},
        {kanji: '手', reading: 'て', meaning: 'hand'},
        {kanji: '足', reading: 'あし', meaning: 'foot'},
        {kanji: '目', reading: 'め', meaning: 'eye'},
        {kanji: '耳', reading: 'みみ', meaning: 'ear'},
        {kanji: '口', reading: 'くち', meaning: 'mouth'},
        {kanji: '歯', reading: 'は', meaning: 'tooth'},
        {kanji: '頭', reading: 'あたま', meaning: 'head'},
        {kanji: '心', reading: 'こころ', meaning: 'heart'},
        {kanji: '本', reading: 'ほん', meaning: 'book'},
        {kanji: '車', reading: 'くるま', meaning: 'car'},
        {kanji: '店', reading: 'みせ', meaning: 'store'},
        {kanji: '家', reading: 'いえ', meaning: 'house'},
        {kanji: '学', reading: 'がく', meaning: 'study'},
        {kanji: '校', reading: 'こう', meaning: 'school'}
    ],
    grade3: [
        {kanji: '悪', reading: 'わるい', meaning: 'bad'},
        {kanji: '安', reading: 'やすい', meaning: 'cheap'},
        {kanji: '暗', reading: 'くらい', meaning: 'dark'},
        {kanji: '医', reading: 'い', meaning: 'doctor'},
        {kanji: '委', reading: 'い', meaning: 'committee'},
        {kanji: '意', reading: 'い', meaning: 'meaning'},
        {kanji: '育', reading: 'いく', meaning: 'raise'},
        {kanji: '員', reading: 'いん', meaning: 'member'},
        {kanji: '院', reading: 'いん', meaning: 'institution'},
        {kanji: '飲', reading: 'のむ', meaning: 'drink'},
        {kanji: '運', reading: 'うん', meaning: 'carry'},
        {kanji: '泳', reading: 'およぐ', meaning: 'swim'},
        {kanji: '駅', reading: 'えき', meaning: 'station'},
        {kanji: '央', reading: 'おう', meaning: 'center'},
        {kanji: '横', reading: 'よこ', meaning: 'side'},
        {kanji: '屋', reading: 'や', meaning: 'shop'},
        {kanji: '温', reading: 'おん', meaning: 'warm'},
        {kanji: '化', reading: 'か', meaning: 'change'},
        {kanji: '荷', reading: 'に', meaning: 'load'},
        {kanji: '界', reading: 'かい', meaning: 'world'}
    ],
    grade4: [
        {kanji: '愛', reading: 'あい', meaning: 'love'},
        {kanji: '案', reading: 'あん', meaning: 'plan'},
        {kanji: '以', reading: 'い', meaning: 'by means of'},
        {kanji: '衣', reading: 'い', meaning: 'clothes'},
        {kanji: '位', reading: 'い', meaning: 'position'},
        {kanji: '囲', reading: 'かこむ', meaning: 'surround'},
        {kanji: '胃', reading: 'い', meaning: 'stomach'},
        {kanji: '印', reading: 'いん', meaning: 'stamp'},
        {kanji: '英', reading: 'えい', meaning: 'English'},
        {kanji: '栄', reading: 'えい', meaning: 'prosperity'},
        {kanji: '塩', reading: 'しお', meaning: 'salt'},
        {kanji: '億', reading: 'おく', meaning: 'hundred million'},
        {kanji: '加', reading: 'か', meaning: 'add'},
        {kanji: '果', reading: 'か', meaning: 'fruit'},
        {kanji: '貨', reading: 'か', meaning: 'goods'},
        {kanji: '課', reading: 'か', meaning: 'lesson'},
        {kanji: '芽', reading: 'め', meaning: 'bud'},
        {kanji: '改', reading: 'かい', meaning: 'reform'},
        {kanji: '械', reading: 'かい', meaning: 'machine'},
        {kanji: '害', reading: 'がい', meaning: 'harm'}
    ],
    grade5: [
        {kanji: '圧', reading: 'あつ', meaning: 'pressure'},
        {kanji: '移', reading: 'い', meaning: 'move'},
        {kanji: '因', reading: 'いん', meaning: 'cause'},
        {kanji: '永', reading: 'えい', meaning: 'eternity'},
        {kanji: '営', reading: 'えい', meaning: 'manage'},
        {kanji: '衛', reading: 'えい', meaning: 'defense'},
        {kanji: '易', reading: 'やすい', meaning: 'easy'},
        {kanji: '益', reading: 'えき', meaning: 'profit'},
        {kanji: '液', reading: 'えき', meaning: 'liquid'},
        {kanji: '演', reading: 'えん', meaning: 'performance'},
        {kanji: '応', reading: 'おう', meaning: 'respond'},
        {kanji: '往', reading: 'おう', meaning: 'go'},
        {kanji: '桜', reading: 'さくら', meaning: 'cherry blossom'},
        {kanji: '恩', reading: 'おん', meaning: 'favor'},
        {kanji: '可', reading: 'か', meaning: 'possible'},
        {kanji: '仮', reading: 'か', meaning: 'temporary'},
        {kanji: '価', reading: 'か', meaning: 'price'},
        {kanji: '河', reading: 'かわ', meaning: 'river'},
        {kanji: '過', reading: 'か', meaning: 'pass'},
        {kanji: '快', reading: 'かい', meaning: 'pleasant'}
    ],
    grade6: [
        {kanji: '異', reading: 'い', meaning: 'different'},
        {kanji: '遺', reading: 'い', meaning: 'remains'},
        {kanji: '域', reading: 'いき', meaning: 'area'},
        {kanji: '宇', reading: 'う', meaning: 'universe'},
        {kanji: '映', reading: 'えい', meaning: 'reflect'},
        {kanji: '延', reading: 'えん', meaning: 'extend'},
        {kanji: '沿', reading: 'えん', meaning: 'along'},
        {kanji: '我', reading: 'われ', meaning: 'I'},
        {kanji: '灰', reading: 'はい', meaning: 'ash'},
        {kanji: '拡', reading: 'かく', meaning: 'expand'},
        {kanji: '革', reading: 'かく', meaning: 'leather'},
        {kanji: '閣', reading: 'かく', meaning: 'cabinet'},
        {kanji: '割', reading: 'わり', meaning: 'divide'},
        {kanji: '株', reading: 'かぶ', meaning: 'stock'},
        {kanji: '干', reading: 'かん', meaning: 'dry'},
        {kanji: '巻', reading: 'まき', meaning: 'roll'},
        {kanji: '看', reading: 'かん', meaning: 'watch'},
        {kanji: '簡', reading: 'かん', meaning: 'simple'},
        {kanji: '危', reading: 'き', meaning: 'danger'},
        {kanji: '机', reading: 'つくえ', meaning: 'desk'}
    ],
    middle: [
        {kanji: '握', reading: 'にぎる', meaning: 'grasp'},
        {kanji: '扱', reading: 'あつかう', meaning: 'handle'},
        {kanji: '宴', reading: 'えん', meaning: 'banquet'},
        {kanji: '延', reading: 'のべる', meaning: 'extend'},
        {kanji: '沿', reading: 'そう', meaning: 'along'},
        {kanji: '概', reading: 'がい', meaning: 'general'},
        {kanji: '各', reading: 'かく', meaning: 'each'},
        {kanji: '拡', reading: 'かく', meaning: 'expand'},
        {kanji: '革', reading: 'かく', meaning: 'revolution'},
        {kanji: '格', reading: 'かく', meaning: 'status'},
        {kanji: '核', reading: 'かく', meaning: 'nucleus'},
        {kanji: '獲', reading: 'かく', meaning: 'capture'},
        {kanji: '確', reading: 'かく', meaning: 'certain'},
        {kanji: '覚', reading: 'かく', meaning: 'remember'},
        {kanji: '較', reading: 'かく', meaning: 'compare'},
        {kanji: '郭', reading: 'かく', meaning: 'enclosure'},
        {kanji: '閣', reading: 'かく', meaning: 'tower'},
        {kanji: '割', reading: 'かつ', meaning: 'divide'},
        {kanji: '株', reading: 'かぶ', meaning: 'stock'},
        {kanji: '釜', reading: 'かま', meaning: 'pot'}
    ],
    common: [
        {kanji: '暴', reading: 'ぼう', meaning: 'violent'},
        {kanji: '望', reading: 'のぞむ', meaning: 'wish'},
        {kanji: '忘', reading: 'わすれる', meaning: 'forget'},
        {kanji: '妄', reading: 'もう', meaning: 'delusion'},
        {kanji: '盲', reading: 'もう', meaning: 'blind'},
        {kanji: '房', reading: 'ぼう', meaning: 'room'},
        {kanji: '肪', reading: 'ぼう', meaning: 'fat'},
        {kanji: '某', reading: 'ぼう', meaning: 'certain'},
        {kanji: '冒', reading: 'ぼう', meaning: 'risk'},
        {kanji: '剖', reading: 'ぼう', meaning: 'dissect'},
        {kanji: '紡', reading: 'ぼう', meaning: 'spin'},
        {kanji: '肋', reading: 'ろく', meaning: 'rib'},
        {kanji: '朗', reading: 'ろう', meaning: 'bright'},
        {kanji: '廊', reading: 'ろう', meaning: 'corridor'},
        {kanji: '浪', reading: 'ろう', meaning: 'wave'},
        {kanji: '漏', reading: 'ろう', meaning: 'leak'},
        {kanji: '老', reading: 'ろう', meaning: 'old'},
        {kanji: '蝋', reading: 'ろう', meaning: 'wax'},
        {kanji: '狼', reading: 'ろう', meaning: 'wolf'},
        {kanji: '篭', reading: 'ろう', meaning: 'basket'}
    ]
}; 