export const kanjiDatabase = {
    grade1: [
        {kanji: '火山', reading: 'かざん', meaning: 'volcano'},
        {kanji: '水田', reading: 'すいでん', meaning: 'rice field'},
        {kanji: '大木', reading: 'たいぼく', meaning: 'big tree'},
        {kanji: '日光', reading: 'にっこう', meaning: 'sunlight'},
        {kanji: '小川', reading: 'おがわ', meaning: 'stream'},
        {kanji: '山道', reading: 'やまみち', meaning: 'mountain path'},
        {kanji: '川原', reading: 'かわら', meaning: 'riverbed'},
        {kanji: '田畑', reading: 'たはた', meaning: 'fields'},
        {kanji: '木陰', reading: 'こかげ', meaning: 'shade of a tree'},
        {kanji: '月夜', reading: 'つきよ', meaning: 'moonlit night'},
        {kanji: '青空', reading: 'あおぞら', meaning: 'blue sky'},
        {kanji: '花火', reading: 'はなび', meaning: 'fireworks'},
        {kanji: '草原', reading: 'そうげん', meaning: 'grassland'},
        {kanji: '星空', reading: 'ほしぞら', meaning: 'starry sky'},
        {kanji: '山林', reading: 'さんりん', meaning: 'mountain forest'},
        {kanji: '水面', reading: 'すいめん', meaning: 'water surface'},
        {kanji: '花道', reading: 'はなみち', meaning: 'flower path'},
        {kanji: '竹林', reading: 'ちくりん', meaning: 'bamboo grove'},
        {kanji: '雪山', reading: 'ゆきやま', meaning: 'snowy mountain'},
        {kanji: '夕焼', reading: 'ゆうやけ', meaning: 'sunset glow'},
        {kanji: '花畑', reading: 'はなばたけ', meaning: 'flower field'},
        {kanji: '森川', reading: 'もりかわ', meaning: 'forest and river'},
        {kanji: '草木', reading: 'くさき', meaning: 'plants'},
        {kanji: '山川', reading: 'やまかわ', meaning: 'mountains and rivers'},
        {kanji: '水車', reading: 'すいしゃ', meaning: 'waterwheel'},
        {kanji: '青葉', reading: 'あおば', meaning: 'fresh leaves'},
        {kanji: '雪原', reading: 'せつげん', meaning: 'snowfield'},
        {kanji: '月見', reading: 'つきみ', meaning: 'moon viewing'},
        {kanji: '竹笛', reading: 'たけぶえ', meaning: 'bamboo flute'},
        {kanji: '花束', reading: 'はなたば', meaning: 'bouquet'},
    ],
    grade2: [
        {kanji: '学校', reading: 'がっこう', meaning: 'school'},
        {kanji: '図書', reading: 'としょ', meaning: 'books'},
        {kanji: '動物', reading: 'どうぶつ', meaning: 'animal'},
        {kanji: '自動車', reading: 'じどうしゃ', meaning: 'car'},
        {kanji: '教室', reading: 'きょうしつ', meaning: 'classroom'},
        {kanji: '先生', reading: 'せんせい', meaning: 'teacher'},
        {kanji: '友達', reading: 'ともだち', meaning: 'friend'},
        {kanji: '家族', reading: 'かぞく', meaning: 'family'},
        {kanji: '運動', reading: 'うんどう', meaning: 'exercise'},
        {kanji: '朝食', reading: 'ちょうしょく', meaning: 'breakfast'},
        {kanji: '昼食', reading: 'ちゅうしょく', meaning: 'lunch'},
        {kanji: '夕食', reading: 'ゆうしょく', meaning: 'dinner'},
        {kanji: '体育', reading: 'たいいく', meaning: 'physical education'},
        {kanji: '音楽', reading: 'おんがく', meaning: 'music'},
        {kanji: '図画', reading: 'ずが', meaning: 'drawing'},
        {kanji: '作文', reading: 'さくぶん', meaning: 'composition'},
        {kanji: '読書', reading: 'どくしょ', meaning: 'reading'},
        {kanji: '遠足', reading: 'えんそく', meaning: 'excursion'},
        {kanji: '運動場', reading: 'うんどうじょう', meaning: 'playground'},
        {kanji: '図書館', reading: 'としょかん', meaning: 'library'},
        {kanji: '教科書', reading: 'きょうかしょ', meaning: 'textbook'},
        {kanji: '黒板', reading: 'こくばん', meaning: 'blackboard'},
        {kanji: '運動会', reading: 'うんどうかい', meaning: 'sports day'},
        {kanji: '給食', reading: 'きゅうしょく', meaning: 'school lunch'},
        {kanji: '校庭', reading: 'こうてい', meaning: 'schoolyard'},
        {kanji: '学年', reading: 'がくねん', meaning: 'grade'},
        {kanji: '時間割', reading: 'じかんわり', meaning: 'timetable'},
        {kanji: '席替え', reading: 'せきがえ', meaning: 'seat change'},
    ],
    grade3: [
        {kanji: '運動会', reading: 'うんどうかい', meaning: 'sports day'},
        {kanji: '図画工作', reading: 'ずがこうさく', meaning: 'arts and crafts'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '理科室', reading: 'りかしつ', meaning: 'science room'},
        {kanji: '音楽会', reading: 'おんがくかい', meaning: 'music concert'},
        {kanji: '体育館', reading: 'たいいくかん', meaning: 'gymnasium'},
        {kanji: '給食当番', reading: 'きゅうしょくとうばん', meaning: 'lunch duty'},
        {kanji: '読書感想', reading: 'どくしょかんそう', meaning: 'book report'},
        {kanji: '遠足日記', reading: 'えんそくにっき', meaning: 'excursion diary'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '自由研究', reading: 'じゆうけんきゅう', meaning: 'independent research'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '読書感想文', reading: 'どくしょかんそうぶん', meaning: 'book report essay'},
        {kanji: '給食時間', reading: 'きゅうしょくじかん', meaning: 'lunch time'},
        {kanji: '図書委員', reading: 'としょいいん', meaning: 'library committee member'},
        {kanji: '学級新聞', reading: 'がっきゅうしんぶん', meaning: 'class newspaper'},
        {kanji: '係活動', reading: 'かかりかつどう', meaning: 'committee activity'},
        {kanji: '運動場', reading: 'うんどうじょう', meaning: 'playground'},
        {kanji: '音読', reading: 'おんどく', meaning: 'reading aloud'},
        {kanji: '図工', reading: 'ずこう', meaning: 'art and crafts'},
        {kanji: '学習発表', reading: 'がくしゅうはっぴょう', meaning: 'learning presentation'},
        {kanji: '自由帳', reading: 'じゆうちょう', meaning: 'free notebook'},
        {kanji: '連絡帳', reading: 'れんらくちょう', meaning: 'communication notebook'},
        {kanji: '朝会', reading: 'ちょうかい', meaning: 'morning assembly'},
    ],
    grade4: [
        {kanji: '理科室', reading: 'りかしつ', meaning: 'science room'},
        {kanji: '音楽会', reading: 'おんがくかい', meaning: 'music concert'},
        {kanji: '体育館', reading: 'たいいくかん', meaning: 'gymnasium'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '図書館', reading: 'としょかん', meaning: 'library'},
        {kanji: '運動場', reading: 'うんどうじょう', meaning: 'playground'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '遠足日記', reading: 'えんそくにっき', meaning: 'excursion diary'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '家庭科', reading: 'かていか', meaning: 'home economics'},
        {kanji: '算数科', reading: 'さんすうか', meaning: 'arithmetic'},
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '読書感想', reading: 'どくしょかんそう', meaning: 'book report'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '社会調査', reading: 'しゃかいちょうさ', meaning: 'social survey'},
        {kanji: '理科観察', reading: 'りかかんさつ', meaning: 'science observation'},
        {kanji: '音楽発表会', reading: 'おんがくはっぴょうかい', meaning: 'music presentation event'},
        {kanji: '家庭訪問', reading: 'かていほうもん', meaning: 'home visit'},
        {kanji: '学級目標', reading: 'がっきゅうもくひょう', meaning: 'class goal'},
        {kanji: '読書週間', reading: 'どくしょしゅうかん', meaning: 'reading week'},
        {kanji: '発表資料', reading: 'はっぴょうしりょう', meaning: 'presentation material'},
        {kanji: '委員活動', reading: 'いいんかつどう', meaning: 'committee activity'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: 'grade meeting'},
        {kanji: '遠足計画', reading: 'えんそくけいかく', meaning: 'excursion plan'},
    ],
    grade5: [
        {kanji: '家庭科', reading: 'かていか', meaning: 'home economics'},
        {kanji: '算数科', reading: 'さんすうか', meaning: 'arithmetic'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '読書感想', reading: 'どくしょかんそう', meaning: 'book report'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '自由研究', reading: 'じゆうけんきゅう', meaning: 'independent research'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '卒業証書', reading: 'そつぎょうしょうしょ', meaning: 'diploma'},
        {kanji: '修了証書', reading: 'しゅうりょうしょうしょ', meaning: 'certificate of completion'},
        {kanji: '卒業文集', reading: 'そつぎょうぶんしゅう', meaning: 'graduation essays'},
        {kanji: '学年主任', reading: 'がくねんしゅにん', meaning: 'grade leader'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '図書委員', reading: 'としょいいん', meaning: 'library committee member'},
        {kanji: '卒業研究', reading: 'そつぎょうけんきゅう', meaning: 'graduation research'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: 'grade meeting'},
        {kanji: '委員活動', reading: 'いいんかつどう', meaning: 'committee activity'},
        {kanji: '発表資料', reading: 'はっぴょうしりょう', meaning: 'presentation material'},
        {kanji: '社会調査', reading: 'しゃかいちょうさ', meaning: 'social survey'},
        {kanji: '理科観察', reading: 'りかかんさつ', meaning: 'science observation'},
        {kanji: '音楽発表会', reading: 'おんがくはっぴょうかい', meaning: 'music presentation event'},
        {kanji: '家庭訪問', reading: 'かていほうもん', meaning: 'home visit'},
        {kanji: '学級目標', reading: 'がっきゅうもくひょう', meaning: 'class goal'},
        {kanji: '読書週間', reading: 'どくしょしゅうかん', meaning: 'reading week'},
    ],
    grade6: [
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '生徒会', reading: 'せいとかい', meaning: 'student council'},
        {kanji: '部活動', reading: 'ぶかつどう', meaning: 'club activities'},
        {kanji: '卒業文集', reading: 'そつぎょうぶんしゅう', meaning: 'graduation essays'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '学年主任', reading: 'がくねんしゅにん', meaning: 'grade leader'},
        {kanji: '卒業証書', reading: 'そつぎょうしょうしょ', meaning: 'diploma'},
        {kanji: '修了証書', reading: 'しゅうりょうしょうしょ', meaning: 'certificate of completion'},
        {kanji: '自由研究', reading: 'じゆうけんきゅう', meaning: 'independent research'},
        {kanji: '社会見学', reading: 'しゃかいけんがく', meaning: 'field trip'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '音楽発表', reading: 'おんがくはっぴょう', meaning: 'music presentation'},
        {kanji: '卒業旅行', reading: 'そつぎょうりょこう', meaning: 'graduation trip'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '図書委員', reading: 'としょいいん', meaning: 'library committee member'},
        {kanji: '卒業研究', reading: 'そつぎょうけんきゅう', meaning: 'graduation research'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: 'grade meeting'},
        {kanji: '委員活動', reading: 'いいんかつどう', meaning: 'committee activity'},
        {kanji: '発表資料', reading: 'はっぴょうしりょう', meaning: 'presentation material'},
        {kanji: '社会調査', reading: 'しゃかいちょうさ', meaning: 'social survey'},
        {kanji: '理科観察', reading: 'りかかんさつ', meaning: 'science observation'},
        {kanji: '音楽発表会', reading: 'おんがくはっぴょうかい', meaning: 'music presentation event'},
        {kanji: '家庭訪問', reading: 'かていほうもん', meaning: 'home visit'},
        {kanji: '学級目標', reading: 'がっきゅうもくひょう', meaning: 'class goal'},
        {kanji: '読書週間', reading: 'どくしょしゅうかん', meaning: 'reading week'},
    ],
    middle: [
        {kanji: '生徒会', reading: 'せいとかい', meaning: 'student council'},
        {kanji: '部活動', reading: 'ぶかつどう', meaning: 'club activities'},
        {kanji: '英語科', reading: 'えいごか', meaning: 'English department'},
        {kanji: '数学科', reading: 'すうがくか', meaning: 'mathematics department'},
        {kanji: '理科実験', reading: 'りかじっけん', meaning: 'science experiment'},
        {kanji: '社会科', reading: 'しゃかいか', meaning: 'social studies'},
        {kanji: '卒業式', reading: 'そつぎょうしき', meaning: 'graduation ceremony'},
        {kanji: '修学旅行', reading: 'しゅうがくりょこう', meaning: 'school trip'},
        {kanji: '学級会', reading: 'がっきゅうかい', meaning: 'class meeting'},
        {kanji: '委員会', reading: 'いいんかい', meaning: 'committee'},
        {kanji: '文化祭', reading: 'ぶんかさい', meaning: 'school festival'},
        {kanji: '体育祭', reading: 'たいいくさい', meaning: 'sports festival'},
        {kanji: '合唱祭', reading: 'がっしょうさい', meaning: 'choral festival'},
        {kanji: '卒業証書', reading: 'そつぎょうしょうしょ', meaning: 'diploma'},
        {kanji: '修了証書', reading: 'しゅうりょうしょうしょ', meaning: 'certificate of completion'},
        {kanji: '卒業文集', reading: 'そつぎょうぶんしゅう', meaning: 'graduation essays'},
        {kanji: '学年主任', reading: 'がくねんしゅにん', meaning: 'grade leader'},
        {kanji: '委員長', reading: 'いいんちょう', meaning: 'committee chair'},
        {kanji: '学芸会', reading: 'がくげいかい', meaning: 'school arts festival'},
        {kanji: '発表会', reading: 'はっぴょうかい', meaning: 'presentation'},
        {kanji: '生徒手帳', reading: 'せいとてちょう', meaning: 'student handbook'},
        {kanji: '学級委員', reading: 'がっきゅういいん', meaning: 'class committee'},
        {kanji: '部活動報告', reading: 'ぶかつどうほうこく', meaning: 'club activity report'},
        {kanji: '文化講演', reading: 'ぶんかこうえん', meaning: 'cultural lecture'},
        {kanji: '進路指導', reading: 'しんろしどう', meaning: 'career guidance'},
        {kanji: '学年集会', reading: 'がくねんしゅうかい', meaning: 'grade meeting'},
        {kanji: '委員活動', reading: 'いいんかつどう', meaning: 'committee activity'},
        {kanji: '卒業研究', reading: 'そつぎょうけんきゅう', meaning: 'graduation research'},
        {kanji: '理科観察', reading: 'りかかんさつ', meaning: 'science observation'},
        {kanji: '社会調査', reading: 'しゃかいちょうさ', meaning: 'social survey'},
    ],
    common: [
        {kanji: '経済学', reading: 'けいざいがく', meaning: 'economics'},
        {kanji: '情報処理', reading: 'じょうほうしょり', meaning: 'information processing'},
        {kanji: '国際化', reading: 'こくさいか', meaning: 'internationalization'},
        {kanji: '環境問題', reading: 'かんきょうもんだい', meaning: 'environmental problem'},
        {kanji: '少子化', reading: 'しょうしか', meaning: 'declining birthrate'},
        {kanji: '高齢化', reading: 'こうれいか', meaning: 'aging population'},
        {kanji: '人工知能', reading: 'じんこうちのう', meaning: 'artificial intelligence'},
        {kanji: '情報社会', reading: 'じょうほうしゃかい', meaning: 'information society'},
        {kanji: '国際交流', reading: 'こくさいこうりゅう', meaning: 'international exchange'},
        {kanji: '科学技術', reading: 'かがくぎじゅつ', meaning: 'science and technology'},
        {kanji: '新幹線', reading: 'しんかんせん', meaning: 'bullet train'},
        {kanji: '携帯電話', reading: 'けいたいでんわ', meaning: 'mobile phone'},
        {kanji: '電子辞書', reading: 'でんしじしょ', meaning: 'electronic dictionary'},
        {kanji: '自動販売', reading: 'じどうはんばい', meaning: 'vending'},
        {kanji: '高速道路', reading: 'こうそくどうろ', meaning: 'expressway'},
        {kanji: '国際空港', reading: 'こくさいくうこう', meaning: 'international airport'},
        {kanji: '情報通信', reading: 'じょうほうつうしん', meaning: 'information communication'},
        {kanji: '経済成長', reading: 'けいざいせいちょう', meaning: 'economic growth'},
        {kanji: '社会保障', reading: 'しゃかいほしょう', meaning: 'social security'},
        {kanji: '国民健康', reading: 'こくみんけんこう', meaning: 'national health'},
        {kanji: '情報管理', reading: 'じょうほうかんり', meaning: 'information management'},
        {kanji: '経済政策', reading: 'けいざいせいさく', meaning: 'economic policy'},
        {kanji: '社会問題', reading: 'しゃかいもんだい', meaning: 'social problem'},
        {kanji: '国際協力', reading: 'こくさいきょうりょく', meaning: 'international cooperation'},
        {kanji: '環境保護', reading: 'かんきょうほご', meaning: 'environmental protection'},
        {kanji: '情報公開', reading: 'じょうほうこうかい', meaning: 'information disclosure'},
        {kanji: '経済活動', reading: 'けいざいかつどう', meaning: 'economic activity'},
        {kanji: '社会福祉', reading: 'しゃかいふくし', meaning: 'social welfare'},
        {kanji: '国民投票', reading: 'こくみんとうひょう', meaning: 'national referendum'},
        {kanji: '科学研究', reading: 'かがくけんきゅう', meaning: 'scientific research'},
    ],
    nando: [
        {kanji: '海月', reading: 'くらげ', meaning: 'jellyfish'},
        {kanji: '木菟', reading: 'みみずく', meaning: 'horned owl'},
        {kanji: '山茶花', reading: 'さざんか', meaning: 'sasanqua camellia'},
        {kanji: '石榴', reading: 'ざくろ', meaning: 'pomegranate'},
        {kanji: '杜若', reading: 'かきつばた', meaning: 'iris'},
        {kanji: '海豹', reading: 'あざらし', meaning: 'seal'},
        {kanji: '鰐梨', reading: 'アボカド', meaning: 'avocado'},
        {kanji: '海豚', reading: 'いるか', meaning: 'dolphin'},
        {kanji: '蒲公英', reading: 'たんぽぽ', meaning: 'dandelion'},
        {kanji: '向日葵', reading: 'ひまわり', meaning: 'sunflower'},
        {kanji: '秋桜', reading: 'こすもす', meaning: 'cosmos'},
        {kanji: '蓬莱', reading: 'ほうらい', meaning: 'paradise'},
        {kanji: '金糸雀', reading: 'かなりあ', meaning: 'canary'},
        {kanji: '時雨', reading: 'しぐれ', meaning: 'drizzle'},
        {kanji: '白粉花', reading: 'おしろいばな', meaning: 'four o’clock flower'},
        {kanji: '鈴蘭', reading: 'すずらん', meaning: 'lily of the valley'},
        {kanji: '躑躅', reading: 'つつじ', meaning: 'azalea'},
        {kanji: '忍冬', reading: 'すいかずら', meaning: 'honeysuckle'},
        {kanji: '風信子', reading: 'ひやしんす', meaning: 'hyacinth'},
        {kanji: '紫陽花', reading: 'あじさい', meaning: 'hydrangea'},
        {kanji: '鶏冠', reading: 'とさか', meaning: 'rooster comb'},
        {kanji: '鶏頭', reading: 'けいとう', meaning: 'cockscomb'},
        {kanji: '鶏魚', reading: 'いさき', meaning: 'grunt fish'},
        {kanji: '鶏冠木', reading: 'けいかんぼく', meaning: 'sumac'},
        {kanji: '鶏冠花', reading: 'けいかんか', meaning: 'celosia'},
        {kanji: '鶏冠草', reading: 'けいかんそう', meaning: 'cockspur grass'},
        {kanji: '鶏冠石', reading: 'けいかんせき', meaning: 'realgar'},
        {kanji: '鶏冠山', reading: 'けいかんざん', meaning: 'Mt. Keikan'},
        {kanji: '鶏冠川', reading: 'けいかんがわ', meaning: 'Keikan River'},
        {kanji: '鶏冠寺', reading: 'けいかんじ', meaning: 'Keikan Temple'},
    ]
}; 